language: ruby
env:
  matrix:
    - "ACTIVE_STAR_VERSION='~> 5.0.0'"
    - "ACTIVE_STAR_VERSION='~> 5.1.0'"
    - "ACTIVE_STAR_VERSION='~> 5.2.2'"
    - "ACTIVE_STAR_VERSION='~> 6.0.0.beta2'"
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.3
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'CREATE USER sequent NOSUPERUSER NOCREATEDB NOCREATEROLE;' -U postgres
  - psql -c 'CREATE DATABASE sequent_spec_db OWNER sequent;' -U postgres
  - bundle exec rake db:create
script:
  - bundle exec rspec
