database: &database
  adapter: postgresql
  host: localhost
  port: 5432
  timeout: 5000
  username: sequent
  password: sequent

spec:
  <<: *database
  database: sequent_spec_db

development:
  <<: *database
  database: freemle_dev_db
